### PR TITLE
trizen removes the clone dir afterwards, no need to manually create a…

### PR DESCRIPTION
**Pull request by edward-shen**
…nd delete temp dir

### CODE REVIEW

**Comment by edward-shen** [comment]
also lol im a contributor to your dot files now

**Comment by kylesferrazza** [comment]
Trizen removes the clone dir but you want me to make the clone dir my home directory?

**Comment by edward-shen** [comment]
Trizen clone into a subdirectory in the specified clone path. It removes
the subdirectory.

**Comment by trizen** [comment]
This is the worst pull-request I've ever seen. Please, just don't merge it.

**Comment by kylesferrazza** [comment]
Thanks for the backup @trizen

**Comment by edward-shen** [comment]
Hey @trizen, thanks for checking in on this PR! I test my changes on a VM and trizen seems to only delete subdirectories it creates when specifying a `--clone-dir` location. Why is setting it to `$HOME` such a bad idea?

**Pull request closed without merging**
